package chausistant;

import java.io.IOException;
import java.nio.file.Path;

import chausistant.command.Command;
import chausistant.exception.ChausistantException;
import chausistant.parser.Parser;
import chausistant.storage.Storage;
import chausistant.task.TaskList;
import chausistant.ui.Ui;

/**
 * Coordinates the chatbot's user interface, storage, task list, and commands.
 */
public class Chausistant {
    private static final Path SAVE_FILE = Path.of("data", "duke.txt");

    private final Path saveFile;
    private final Storage storage;
    private final Ui ui;
    private TaskList tasks;
    private boolean hasLoadedTasks;

    /** Creates a chatbot that stores tasks in the project's default data file. */
    public Chausistant() {
        this(SAVE_FILE);
    }

    /** Creates a chatbot that stores its tasks at the supplied file path. */
    public Chausistant(Path saveFile) {
        this.saveFile = saveFile;
        ui = new Ui();
        storage = new Storage(saveFile);
        tasks = new TaskList();
    }

    /** Starts the chatbot and processes commands until the user exits. */
    public void run() {
        ui.showWelcome();
        loadTasks(ui);

        while (ui.hasNextCommand()) {
            String fullCommand = ui.readCommand();
            if (fullCommand.isEmpty()) {
                continue;
            }

            if (processCommand(fullCommand, ui)) {
                break;
            }
        }
    }

    /**
     * Processes one command and returns the resulting user-facing response.
     *
     * @param fullCommand command to process
     * @return response generated by the command or validation error
     */
    public String getResponse(String fullCommand) {
        StringBuilder response = new StringBuilder();
        Ui responseUi = new Ui(response);
        loadTasks(responseUi);
        processCommand(fullCommand.strip(), responseUi);
        return response.toString().strip();
    }

    /** Loads saved tasks once while letting the user know about recoverable loading problems. */
    private void loadTasks(Ui outputUi) {
        if (hasLoadedTasks) {
            return;
        }

        try {
            Storage.LoadResult loadedTasks = storage.load();
            tasks = loadedTasks.getTasks();
            for (String warning : loadedTasks.getWarnings()) {
                outputUi.showError(warning);
            }
        } catch (IOException error) {
            outputUi.showError("I could not load your tasks from " + saveFile + ".");
        }
        hasLoadedTasks = true;
    }

    /** Processes one command and returns whether it ends the console session. */
    private boolean processCommand(String fullCommand, Ui outputUi) {
        if (fullCommand.isBlank()) {
            return false;
        }

        try {
            Command command = Parser.parse(fullCommand);
            command.execute(tasks, outputUi, storage);
            return command.isExit();
        } catch (ChausistantException error) {
            outputUi.showError(error.getMessage());
        } catch (IOException error) {
            outputUi.showError("I could not save your tasks to " + saveFile + ".");
        }
        return false;
    }

    /** Starts the chatbot using the project's relative data-file path. */
    public static void main(String[] args) {
        new Chausistant(SAVE_FILE).run();
    }
}
